### ISSUE TITLE
Advanced Processing Lab - Big Data Assignment Task Selection

### ISSUE THREAD

**Issue by kosmasK** [MTG/metadb#1]
I would like to work with the musicbrainz (tags, artist/release metadata) annotation list for the data selection task. 

Student: Kosmas Kritsis

**Comment by alastair** [comment]
Cool, sounds good.
You can see I've added an example data collector for lastfm: https://github.com/MTG/metadb/blob/master/metadb/scrapers/lastfm.py
You should provide a similar file with a `scrape` method which collects the data.

You can test it by using the lookup program which is also included: https://github.com/MTG/metadb/blob/master/lookup.py and run it like this:

```
python lookup.py metadb.scrapers.lastfm <a musicbrainz id> <artist name> <song name>
```

e.g., here is a musicbrainz id: http://musicbrainz.org/recording/82d8444b-3478-480c-8652-bf8aa6cb3dc5

## 

As the MusicBrainz task is quite simple, it'd be a good idea to extend this task a little bit. Either
- collect data for a large subset of the acousticbrainz database (this will take a while, but I have some tools to help) and build a model like the first last.fm data task
- or find another website which provides this kind of data and scrape this as well

**Comment by alastair** [comment]
Done and merged
